### ISSUE TITLE
fontawesome plist and ttf not copied. Do you have the same problem when using pod?

### ISSUE THREAD

**Issue by steve21124** [waterlou/WTGlyphFontSet#1]
pod 'WTGlyphFontSet'
pod 'WTGlyphFontSet/fontawesome'

**Comment by waterlou** [comment]
Just tested, no problem.  Which version your cocoapod said installed? mine is 0.6.  May you can try to specify the version:

pod 'WTGlyphFontSet', '~>0.6'
pod 'WTGlyphFontSet/fontawesome', '~>0.6'

BTW, my pod version is  0.20.2

**Comment by steve21124** [comment]
My pod version is 0.20.2
hmm... interesting... I will checkout later tonight....

**Comment by steve21124** [comment]
sorry. it is there... in resource folder. I miss that folder. closing the issue
